name             'RepoDev'
maintainer       'Dmytro Fadyeyenko'
maintainer_email 'dmytro.fadyeyenko@globallogic.com'
license          'GL'
description      'Repo dev machine'
long_description 'Dev machine for repo for vagrant & gem'
version          '0.1.0'
issues_url       'email only'
source_url       'https://github.com/dfad1ripe/df_devops_repodev'
version          '0.1.0'
depends          'selinux'
depends          'apache2'
depends          'php'
depends          'onddo_proftpd'
depends          'iptables'
